Map<String, String> fr = {
  "espace_enfants": "Espace Enfants",
  "espace_parents": "Espace Parents ",
  "email": "E-mail",
  "password": " Mot de passe ",
  "entrer_votre_email": "Entrer votre Email",
  "entrer_votre_password": "Entrer votre Mot de passe",
  "mot_de_passe_oublié": "Mot de passe oublié?",
  "se_connecter ": "Se connecter",
  "register": "Vous n'avez pas de compte? S'inscrire",
  "nom": " Nom",
  "confirmer_le_mot_de_passe": " Confirmer le mot de passe ",
  "creer_compte": " Créer un compte",
  "connecte": " Se connecter en tant qu'administrateur",
  "ajt_enfant": "Ajouter Enfant",
  "pseudo": "Pseudo",
  "emailenfant": "emailenfant ",
  "genre": "Genre",
  "garcon": "Garçon",
  "fille": "Fille",
  "valider": "Valider",
  "ajtr_enf": "Ajouter un enfant",
  "liste_enfs": "Liste des enfants",
  "bienvenue": "Bienvenue",
  "profile": "Profile",
  "resources": "Ressources",
  "quiz": "Quiz",
  "evenement": "Evenement",
  "parametre": "Paramétres",
  "logout": "Se déconnecter",
  "ressources_pr_parent": "Ressources pour les parents",
  "dix_consiels": "Dix conseils pour communiquer avec un enfant autiste.",
  "rgl1": " Favorisez des jeux en lien avec les intérêts de l’enfant.",
  "regl2":
      "Mettez-vous à la hauteur de l’enfant, afin de favoriser une communication face à face et faciliter l’échange.",
  "regl3": " Mettez l’accent sur les mots importants",
  "regl4": "Utilisez des supports visuels (gestes, photos, images)",
  "regl5":
      " Ajustez votre niveau de langage à celui de l’enfant, en utilisant des énoncés juste un peu plus longs que ceux qu’il produit.",
  "regl6":
      " Répétez souvent les mêmes mots, dans différents contextes, afin de favoriser l’apprentissage du vocabulaire.",
  "regl7":
      "Parlez beaucoup de ce que qu’on fait, ou de ce que l’enfant fait, afin de donner des modèles de petits énoncés adéquats.",
  "regl8":
      "Exagérez les expressions et les exclamations pour susciter une réaction chez l’enfant.",
  "regl9":
      "Stimulez la communication dans des contextes naturels de la vie quotidienne (ex : lors des repas, du bain, des jeux).",
  "regl10": "Gardez en tête que la communication se stimule dans le plaisir.",
  "adrs_nmr_de_professionnels": "Adresses et numéros de professionnels :",
  "psy": "Psychologues spécialisés",
  "centre_des_enfs": "Centre des enfants autiste : ",
  "music": "Playlist de musique apaisante : ",
  "ectr_playliste": "Écoutez notre playlist de musique relaxante sur Spotify ",
  "jeux_pour_les_enfants_autistes": "Jeux pour les enfants autistes : ",
  "jeux1":"Jouez à des jeux interactifs sur Autisme-Education",
  "jeux2":"Découvrez des jeux éducatifs sur Autism Speaks",
  "information_enfant":"Information sur l’enfant  ",
  "mode_sombre":"Mode sombre",
  "activer_mode_sombre":"Activer le thème sombre pour une meilleure lecture nocturne. ",
  "activation_notification":"Activer les notifications ",
  "notification":"Recevez des notifications pour les mises à jour et les annonces. ",
  "etat_activité": "Afficher l’état de l’activité",







//traduction met3hom
  "short_name": "The name is short",

  "forget_password_message":
      "Please enter your email address to reset your password",
  "forget_password?": "forget password?",
  
  "empty_email": "Please insert a email",
  "short_email": "The email is short",
  "empty_password": "Please insert a password",
  "short_password": "The password is short",
  "not_match_password": "The password doesn't match",
  "where_Do_you_want_go": "Where Do You Want Go?",
  "search_trip": "Search your trip",
  "search_hotels": "Search Hotels",
  "city_hotels": "City / Hotels",
  "check_in": "Check-in",
  "check_out": "Check-out",
  "guest_details": "Guest Details",
  "adults": "Adults",
  "room": "Room",
  "infants": "Infants",
  "children": "Children",
  "Economy": "Economy",
  "Premium_Economy": "Premium Economy",
  "Business": "Business",
  "First": "First",
  "Ok": "Ok",
  "Search": "Search",
  "Popular_Categories": "Popular Categories",
  "Something_wrong": "Something is wrong!",
  "Starting_at": "Starting at",
  "Book_Now": "Book Now",
  "reviews": "reviews",
  "Overview": "Overview",
  "Details": "Details",
  "Reviews": "Reviews",
  "Costs": "Costs",
  "Hotels": "Hotels",
  "empty_result": "Not fonund any item",
  "per_night": "/per night",
  "Days": "Days",
  "Duration": "Duration",
  "KM": "KM",
  "Distance": "Distance",
  "Home": "Home",
  "Compass": "Compass",
  "Notifications": "Notifications",
  "Profile": "Profile",
  "Add New Card": "Add New Card",
  "Card Holder": "Card Holder",
  "Enter Informaton": "Enter Informaton",
  "Card Number": "Card Number",
  "Enter card holder name": "Enter card holder name",
  "Expiration Date": "Expiration Date",
  "CVC": "CVC",
  "empty_card_number": "Please enter card number",
  "short_card_number": "Card number is too short",
  "empty_card_holder": "Please enter card holder",
  "short_card_holder": "Card holder is too short",
  "empty_CVC": "Please enter CVC",
  "short_CVC": "CVC is too short",
  "Save": "Save",
  "Save Changes": "Save Changes",
  "enter_valid_number": "Please enter valid number",
  "Something is wrong": "Something is wrong!",
  "Mark as default card": "Mark as default card",
  "Account": "Account",
  "Edit account": "Edit account",
  "Account Security": "Account Security",
  "Add a new card": "Add a new card",
  "Help": "Help",
  "Logout": "Logout",
  "Edit Account": "Edit Account",
  "Change Profile Picture": "Change Profile Picture",
  "Name": "Name",
  "Location": "Location",
  "Address": "Address",
  "Phone Number": "Phone Number",
  "Choosing picture from :": "Choosing picture from :",
  "Gallery": "Gallery",
  "Camera": "Camera",
  "Currency Converter": "Currency Converter",
  "Converter": "Converter",
  "USD": "USD",
  "EUR": "EUR",
  "Continue": "Continue",
  "Enter amount": "Enter amount",
  "Convert": "Convert",
  "Please enter an amount": "Please enter an amount",
  "Please enter a valid amount": "Please enter a valid amount",
  "The result :": "The result :",
  "Change Language": "Change Language",
  "Refresh": "Refresh",
  "Error": "Error",
  "Success": "Success",
  "Please try again another time": "Please try again another time",
  "Please check your email": "Please check your email",
  "Choose Your Language": "Choose Your Language",
};
