name: myfirstapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  http: 1.2.1

  # Remplacez les dépendances MongoDB par les dépendances Firebase appropriées
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9



  mysql1: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg 
    - assets/logo.jpg
    - assets/conseil.png
    - assets/lister.png
    - assets/calendrier.png
    - assets/quiz.png
    - assets/back_button_image.png
    - assets/h.jpg
    - assets/settings.png
    - assets/clothes.png
    - assets/colors.png
    - assets/feelings.png
    - assets/food.png
    - assets/medicin.png
    - assets/numbers.png
    - assets/pronouns.png
    - assets/question.png
    - assets/verbs.png
    - assets/vehiculs.png
    - assets/phrases.png
    - assets/activity.png
    - assets/0.jpg
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/6.jpg
    - assets/7.jpg
    - assets/8.jpg
    - assets/9.jpg